### ISSUE TITLE
Can I use methylstar in mouse?

### ISSUE THREAD

**Issue by kimchuna** [jlab-code/MethylStar#10]
It seems that only TAIR10_chr_all.fa is used as the reference genome. Do you have any plans to put mm10 ㅡmouse genome or hg38 human genome into your docker image?

**Comment by shahryary** [comment]
Yes, it's possible to use any other reference genome in the MethylStar; you just need to copy the reference genome inside of "/home/shared/reference_genome/" directory in docker and change the default to the new one in "Configuration" then "Path: Reference Genome".

Note: The easy way to copy the reference genome inside the docker is (in case if you can't connect to the internet to download directly from internet) copy the reference genome before running the docker. 
To be more precise, before running the docker "docker run --rm -it --privileged -v /PATH/TO/RAWDATA/ .... " command, copy the reference genome into "/PATH/TO/RAWDATA/"  and run the docker, you can find your reference genome in "/data" folder inside the docker container.
