### ISSUE TITLE
Trimmomatic

### ISSUE THREAD

**Issue by mmageroy** [jlab-code/MethylStar#14]
Hi,
I am trying to run spruce WGBS through your pipeline.

Is it possible to run the pipeline without Trimmomatic? My reads are fairly have quality and the adaptors have been trimmed already. I am also having trouble with Trimmomatic not giving any output. See below.

Thanks!
Melissa

>>1
Configuration Summary:

Configured Java location: /usr/bin/java
Trimmomatic path: /home/software/Trimmomatic-0.38
Trimmomatic Adapter: /home/software/Trimmomatic-0.38/adapters/TruSeq3-PE.fa
Trimmomatic Running mode: PE
Trimmomatic ILLUMINACLIP: 1:30:9
Trimmomatic LEADING: 20
Trimmomatic TRAILING: 20
Trimmomatic SLIDINGWINDOW: 4:20
Trimmomatic MINLEN: 36
Trimmomatic Threading: 16
Parallel mode is: Disabled

Do you want continue to run? [y/n] y

Running Trimmomatic Part...

 Starting Trimmomatic ...
Running Trimmomatic for  /data/V300033699_L1_PL2003110001-2_2.fq.gz
V300033699_L1_PL2003110001-2_2 : at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
Trimmomatic finished. Duration 0 Minutes.
Running Trimmomatic for  /data/V300033699_L1_PL2003110001-2_1.fq.gz
V300033699_L1_PL2003110001-2_1 : at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
Trimmomatic finished. Duration 0 Minutes.
Trimmomatic finished. Total time 0 Minutes.

Processing files is finished, You can check the log files in Menu, part 'Trimmomatic-log'

>>  2

---------------------------------------------------------------------------

        *** Running FastQC Report Part ***

Configuration Summary:

- Fastq Path: /home/software/FastQC/fastqc
- Parallel mode is: Disabled

Do you want continue to run? [y/n] y

Running FastQC reports ...
ls: cannot access '/results/trimmomatic-files/*.gz': No such file or directory

Starting Fasqc-report ...
Running in single mode. (parallel mode disabled.)

QC report finished in 0 minutes.
You can find the results in /results/qc-fastq-reports folder.

sort: cannot read: /results/qc-fastq-reports/list-finished.lst: No such file or directory
rm: cannot remove '/results/qc-fastq-reports/list-finished.lst': No such file or directory

Processing files are finished.

Please, press ENTER to continue ...

**Comment by shahryary** [comment]
Hi @mmageroy 

Thank you for using our pipeline. 

Yes, it is possible to run if you already have Trimmomatic files. Please copy your trimmomatic output files into `"Pipeline-RESULT-PATH/ trimmomatic-files/"` then run the pipeline and select either "Run QC-Fastq-report" or "Run Bismark Mapper". The pipeline will read all the files from the "trimmomatic-files" directory and will start to run QC or Bismark-mapper. 

Regarding the error message, I think the  "trimmomatic-files" directory is empty, and when FASTQ is trying to read the files from that directory, you are getting this message. So, if you copy the files as I explained above, it should solve your problem. 

Please let me know if you have any questions.
