### ISSUE TITLE
No files found

### ISSUE THREAD

**Issue by PalmaGudiel** [jlab-code/MethylStar#15]
Hi, 

I found your MethylStar paper and pipeline while searching for straightforward methods for WGBS data preprocessing and I was particularly drawn to it since it is specifically mentioned that it is suitable for both experts and non-experts (I fall in the latter category). I am very used to work with R programming, but I am completely new to the ubuntu/bash environment so my question might be rather dumb!

While changing the configuration to set the proper paths to each requested file, I noticed that MethylStar is not recognizing my .fastq files, any idea why would that be?
After specifying the corresponding path in the first step of the configuration "1. Path: RAW files" I get the following messages:

_Founded 0 files in the directory._

_Also, the size of your data-set almost: 4.8G_

So, my 920 .fastq files do take up almost 4.8G but MethylStar does not seem to be recognizing the individual files as suitable input raw files.

I have tried running the first step of the pipeline (trimmomatic) but I get the following error messages:
 _Starting Trimmomatic ...
Trimmomatic finished. Total time 0 Minutes.
sort: cannot read: /home/palmagudiel/export_results/trimmomatic-files/list-finished.lst: No such file or directory
rm: cannot remove '/home/palmagudiel/export_results/trimmomatic-files/list-finished.lst': No such file or directory
Something went wrong...
something is going wrong... please run again._

But I don't really know if that's related to the "founded 0 files" issue or if it's completely unrelated.

Thank you very much in advance!!

**Comment by shahryary** [comment]
Hi @PalmaGudiel  
Thank you for using our pipeline; 
As I understand, the problem is in the path directory of raw files; in other words, you can't pass just the file path to the pipeline; you should **create a folder** for your raw files and then give that folder path to the pipeline. For instance, create a folder in /home/palmagudiel/rawFiles/ and copy all the fasta files into there; you should pass **/home/palmagudiel/rawFiles/** to the pipeline. 
Hopefully, it solves your problem.

**Comment by PalmaGudiel** [comment]
Hi @shahryary 
Thank your for your fast reply.
I had already given the folder path to the pipeline (please see caption below).

<img width="413" alt="raw files path" src="https://user-images.githubusercontent.com/60005980/119504669-33381b80-bd3a-11eb-8980-de88fac20366.png">

I have also been checking the video tutorial for every step of the way, it's been useful to watch for other issues, just not for this particular one.

**Comment by shahryary** [comment]
@PalmaGudiel  thanks for your reply; 
Could you please send me: 
1- all the configuration parameters (from main menu --> 'C' --> number 10 "see configured parameters"). 
2- in linux bash please do `ls -lah` and send just head of lists. 
Thanks.

**Comment by PalmaGudiel** [comment]
Yes, of course! 

Please keep in mind that I am still at the beginning of the pipeline, I am aware that there might be several unresolved issues other than the problem with the raw files location/identification.

1) Configuration parameters:

Here is a summary of my current configuration parameters (it's a work in progress, right now I am focusing on being able to run at least the trimmomatic part):

- RAW files location: /home/palmagudiel/fastq/
- Number and Size of the data-set: 0 Files and Total size: 4.8 Gigabyte
- The directory of results: /home/palmagudiel/export_results
- Genome type: Human
- Genome folder location: /home/palmagudiel/MethylStar
     -- Genome Reference name: _((I am still trying to figure out where to obtain this file))_
- Paired End: Disabled
- Trimmomatic location: /usr/share/trimmomatic/
     -- JAVA path: /usr/lib/jvm/java-16-openjdk-amd64/bin/java
     -- ILLUMINACLIP: /usr/share/trimmomatic//adapters/TruSeq3-PE.fa:1:30:9
     -- LEADING: 20
     -- TRAILING: 20
     -- SLIDINGWINDOW: 4:20
     -- MINLEN: 36
     -- Number of Threads: 8
- QC-Fastq path: software/FastQC/fastqc
- Bismark parameters: /software/Bismark
     -- scBS-Seq (--pbat)? Disabled
     -- Nucleotide status: false
     -- Number of Parallel: 8 Threads.
     -- Buffer size: 40 Gigabyte.
     -- Samtools Path: /bin/samtools
     -- Bedtools Path: /usr/bin/bedtools
     -- Intermediate for MethExtractor: Disabled
- Methylation extraction parameters( Only for quick run)
     -- Minimum read coverage: 1
- Methimpute Part:
     -- Methimpute Intermediate : Enabled
     -- Methimpute probability(Intermediate): constrained
     -- Methimpute Fit reports: Enabled
     -- Methimpute Enrichment plots: Enabled
     -- Methimpute Full report: Enabled
     -- Methimpute Context: All
- Parallel mode is: Disabled
- E-mail notification: Disabled
- MethylStar version: 1.1.1

2) ls -lah (you meant in the fastq folder with the raw files, right?)

![image](https://user-images.githubusercontent.com/60005980/119507943-48fb1000-bd3d-11eb-95e4-2b8f2fd1a09f.png)

Thanks again!

**Comment by shahryary** [comment]
@PalmaGudiel  thanks for sharing the configs. 
I see the problem; the Pipeline reads all the files in zip format (usually trimmomatic use this format to improve performance), so all your files should be converted into `fastq.gz` format. It's easy; you can do it with linux: go inside of the raw folder and run `gzip *.fastq`.
It should zip all the files inside of the folder. 
Now, you can re-config the path. 
+ I see you didn't configure the `QC-Fastq path` if you need the report, you should configure this option too.
