### ISSUE TITLE
Python NoSectionError while browsing menu

### ISSUE THREAD

**Issue by lardenoije** [jlab-code/MethylStar#4]
Hi,

I get an error when I try to configure the pipeline. When starting MethylStar, I go to C. Configuration > 1. Path: RAW files, after which I get this error:

```
ERROR:root:Traceback (most recent call last):
  File "MethylStar/src/py/configuration.py", line 219, in raw_dataset
    if confirm("GENERAL", "raw_dataset", 3):
  File "MethylStar/src/py/configuration.py", line 191, in confirm
    str_conf = read_config(config_section, config_value)
  File "MethylStar/src/py/globalParameters.py", line 87, in read_config
    val_str = config.get(section, get_string)
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'GENERAL'
```

Other menu items give similar errors. I am using Python version 2.7.5 on a CentOS 7 cluster.
Do you maybe know how to resolve this?

Thanks,
Roy

**Comment by shahryary** [comment]
Hi, 
Please be sure that you have **write** permission on MethylStar directory. To solve this problem please copy "pipeline.conf" from Github(https://github.com/jlab-code/MethylStar/tree/master/config) into MethylStar/config/ directory. 
Also, please specify python version before running the Pipeline. _$python2 run.py_

**Comment by lardenoije** [comment]
Hi,

Thanks, I have write permission on the MethylStar directory, the "pipeline.conf" file and I specified the python version.
However, I did find what caused this issue; I started MethylStar with "python2 path/to/MethylStar/run.py", but if I first go to the MethylStar directory, and then use "python2 run.py" it works.
