### ISSUE TITLE
Plant dna methylation 

### ISSUE THREAD

**Issue by sekhwal** [jlab-code/MethylStar#8]
Does the pipeline work for dna methylation data analysis in plants?

**Comment by shahryary** [comment]
Yes, you can use the MethylStar pipeline to analysis Whole-Genome Bisulfite Sequencing which we tested on Arabidopsis, Maize and rice data-sets.
For more info, here is the link to the paper:  [https://rdcu.be/cblXA](https://rdcu.be/cblXA)
