### ISSUE TITLE
NoSectionError: No section: 'GENERAL'

### ISSUE THREAD

**Issue by marcovth** [jlab-code/MethylStar#9]
Unfortunately, on two different linux machines, I am getting the same python error with clean installs ...
_BTW, I am getting the exact same error when I run the docker instance through singularity._

C >>  1

---------------------------------------------------------------------------

        *** In this part you can specify your data-set location ***

If you have data-set in pair-end mode, you have to give the pattern of extension.

ERROR:root:Traceback (most recent call last):
  File "/project/6029819/marcovth/ecoli/MethylStar/src/py/configuration.py", line 219, in raw_dataset
    if confirm("GENERAL", "raw_dataset", 3):
  File "/project/6029819/marcovth/ecoli/MethylStar/src/py/configuration.py", line 191, in confirm
    str_conf = read_config(config_section, config_value)
  File "/project/6029819/marcovth/ecoli/MethylStar/src/py/globalParameters.py", line 87, in read_config
    val_str = config.get(section, get_string)
  File "/home/marcovth/miniconda3/envs/MethylStar/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'GENERAL'

Something is going wrong... please run again.

**Comment by marcovth** [comment]
Is there a way to start MethylStar through commandline parameters? I can not run it through sbatch as an interactive program.

**Comment by shahryary** [comment]
Hi @marcovth 

Thank you very much for using our pipeline, I updated the Docker image, please download and re-run again. 
We are still working on scripts that you can submit through the queue-based system.

**Comment by marcovth** [comment]
Thanks for the service.

I had to make some adjustments but I got my ecoli test-run started with singularity instead of docker ...

# ... Docker image
# // wget http://jlabdata.org/methylstar.tar.gz

# Can't run MethylStar with sbatch, therefore Interactive instance is the only option ... 
salloc --time=12:0:0 --ntasks=48 --mem-per-cpu=3G --account=def-rmarcott

module load singularity
# singularity build methylstar.sif docker-archive://methylstar.tar.gz
export SINGULARITY_BUILD_PROCESSORS=48
singularity run -B /project/6029819/marcovth/ecoli/:/ecoli  methylstar.sif

# Perl is giving warnings, this should fix that ...
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
locale-gen en_US.UTF-8

cd /ecoli/MethylStar
./run.py

Trimommatic, fastqc working well.
bismark currently running.

[GENERAL]
firstRun=false
currversion=1.1.1
raw_dataset=/ecoli/fastq
result_pipeline=/ecoli/mstar_results
genome_ref=/ecoli/Genome
genome_name=Ecoli.fa
genome_type=Others
docker_mode=false
parallel_mode=true
npar=0
fastq_path=/home/software/FastQC/fastqc
number_of_dataset=2
dataset_size=9.7
pairs_mode=true
first_pattern=_1.fastq.gz
secnd_pattern=_2.fastq.gz

[Trimmomatic]
java_path=/usr/bin/java
trim_path=/home/software/Trimmomatic-0.38
trim_jar=/home/software/Trimmomatic-0.38/trimmomatic-0.38.jar
dir_adap=$trim_path/adapters
name_adap=/home/software/Trimmomatic-0.38/adapters/TruSeq3-SE.fa
end_mode=PE
ill_clip=1:30:9
LEADING=20
TRAILING=20
SLIDINGWINDOW=4:20
MINLEN=36
n_th=8

[Bismark]
bismark_path=/home/software/Bismark-0.20.1
samtools_path=/home/software/samtools-1.9/samtools
bedtools_path=/home/marcovth/miniconda3/envs/MethylStar/bin/bedtools
modified_time=1539787258
bis_parallel=8
buf_size=40
Nthreads=48
nucleotide=false
intermediate_files=false
run_pair_bismark=true
deduplicate=-p
methextractor=-p
del_inter_file=true
single_cell=false
directional=

Warnings ....

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_CA.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_CA.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

**Comment by shahryary** [comment]
Ignore the warning output, It's just some output when trying to install GNU-parallel.
